<a href="https://colab.research.google.com/github/Cyrus-spc-tech/Python/blob/main/Numpyfull.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#2d array
a=np.array([[1,2,3],[1,2,3]])
print(a)
#dimension
print(a.ndim)
#shape
print(a.shape)
#data type
print(a.dtype)
# no of bytes occupied
print(a.itemsize)#or nbytes
#size
print(a.size)
#type
print(type(a))


[[1 2 3]
 [1 2 3]]
2
(2, 3)
int64
8
6
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7,7,8,8],[1,2,3,3,5,6,7,3,8,8]])
print(a)
print()
print(a[1,9])
print()
#1 row
print(a[0,:])
print()
#1 column
print(a[:,0])
print()
# acessing like [starting:ending:stepsize]
print(a[0,1:10:2])
print()
#chanding value
a[0,0]=10
a[1,1]=10
a[1,9]=10
print(a)


[[1 2 3 4 5 6 7 7 8 8]
 [1 2 3 3 5 6 7 3 8 8]]

8

[1 2 3 4 5 6 7 7 8 8]

[1 1]

[2 4 6 7 8]

[[10  2  3  4  5  6  7  7  8  8]
 [ 1 10  3  3  5  6  7  3  8 10]]


In [ ]:
#3x3 matrix
o=np.zeros([3,3])
on=np.ones([3,3])
any=np.full([3,3],55)
print(o)
print()
print(on)
print()
print(any)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [ ]:
#random number
import numpy as np
ran=np.random.random(100)
number_of_guesses = 0

print(f"Welcome! Let's play a number guessing game.")
while True:

    user_guess = int(input("Guess a number between 1 and 100: "))
    if user_guess == ran:
        print(f" Congratulations, You guessed the number in {number_of_guesses} attempts.")
        break
    elif user_guess < ran:
        print("Your guess is too low. Try again!")
    else:
        print("Your guess is too high. Try again!")
    number_of_guesses += 1

In [ ]:
# random values matrix
import numpy as np
a=np.random.random([3,3])
print(a)

[[0.9062759  0.1389588  0.0467841 ]
 [0.38751691 0.85194568 0.727868  ]
 [0.76902393 0.15677498 0.44173396]]


In [ ]:
# random integer values matrix
import numpy as np
a=np.random.randint(1,100,[3,3])
print(a)

[[60 52 93]
 [28 96 97]
 [96 87 57]]


In [ ]:
# making a identity matrix
import numpy as np
a=np.eye(3)
b=np.identity(3)
print(a)
print()
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#making matrix not using actual matrix
r=np.ones([5,5])
z=np.zeros([3,3])
z[1,1]=9

r[1:4,1:4]=z
print(r)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#copying the array
a=np.array([[1,2,3],[4,5,6]])
x=np.array([4,5,6,7])
y=x
print(x)
y[0]=100
print(y)
print(x)
#x also chnges


print()
#.copy creates a virtual copy
b=a.copy()
b[0,0]=100
print(a)
print()
print(b)

[4 5 6 7]
[100   5   6   7]
[100   5   6   7]

[[1 2 3]
 [4 5 6]]

[[100   2   3]
 [  4   5   6]]


In [ ]:
#using maths
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print()

#simple maths
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)
print(a%2)
print(a//2)
print()
#array maths
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)
print(a//b)
print()
#trigno matrix
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))
print(np.exp(a))

#  https://numpy.org/doc/stable/reference/routines.math.html

[1 2 3 4]

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[1 0 1 0]
[0 1 1 2]

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[1 2 3 4]
[0 0 0 0]

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
#matrix multiply
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])
c=np.array([[1,2,3],[1,2,1],[1,1,3]])


mul=a.dot(b)
mul1=np.matmul(a,b)


print(mul1)
print()
print(mul)
print()
#to find determinant of a sq matrix
print(np.linalg.det(c))
print(np.linalg.inv(c))
print(np.linalg.eig(c))
#https://numpy.org/doc/stable/reference/routines.linalg.html


[[22 28]
 [49 64]]

[[22 28]
 [49 64]]

-2.0
[[-2.5  1.5  2. ]
 [ 1.  -0.  -1. ]
 [ 0.5 -0.5 -0. ]]
EigResult(eigenvalues=array([ 4.89510652, -0.29240159,  1.39729507]), eigenvectors=array([[ 0.67882428,  0.92785901, -0.04710549],
       [ 0.43803703, -0.32486038, -0.83399463],
       [ 0.5893396 , -0.18314857,  0.54975816]]))


In [ ]:
# doing statics operation
a=np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(np.sum(a))
print()
print(np.min(a))
print()
print(np.max(a))
print()
print(np.mean(a))
print()
print(np.median(a,axis=1))
print()
print(np.std(a))
print()
print(np.var(a))
print()
print(a.T)
print()
print(a.flatten())
print()
print(a.ravel())

[[1 2 3]
 [4 5 6]]

21

1

6

3.5

[2. 5.]

1.707825127659933

2.9166666666666665

[[1 4]
 [2 5]
 [3 6]]

[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [ ]:
#reshaping the matrix
a=np.array([[1,2,3],[4,5,6]])

print(a)
print()
print(a.reshape(3,2))

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],
            [4,'hello',6],
            [7,8,9]])
print(a)
print()
print(a[1][1])
print()
print(a.dtype)


[['1' '2' '3']
 ['4' 'hello' '6']
 ['7' '8' '9']]

hello

<U21


In [ ]:
import numpy as np
a=np.full((10,10),4)
b=np.full((2,2,1),2)
c=np.zeros((3,3))
d=np.ones((3,3))
e=np.empty((2,3))
print(b)
print()
print(a)
print()
print(c)
print()
print(d)
print()
print(e)

[[[2]
  [2]]

 [[2]
  [2]]]

[[4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[2.e-323 2.e-323 2.e-323]
 [2.e-323 2.e-323 2.e-323]]


In [ ]:
import numpy as np
a=np.nan
print(a)
print()
b=np.inf
print(b)

print(np.sqrt(-1))
print()
print(np.array([10])/0)

nan

inf
nan

[inf]


<ipython-input-26-872d4288d518>:8: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
<ipython-input-26-872d4288d518>:10: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


In [ ]:
import numpy as np
a=np.arange(10,100,2)
b=np.linspace(10,100,10)#divides evenly
print(a)
print()
print(b)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print()
b=np.append(a,[[7,8,9]])
print(b)
print()
c=np.insert(a,1,[10,11,12])
print(c)
print()
print(np.stack((a,a)))
print()
print(np.hstack((a,a)))
print()
np.vstack((a,a))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6 7 8 9]

[ 1 10 11 12  2  3  4  5  6]





array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np
# a=np.array([[1,2,3],[4,5,6]])
# print(a)
guess=0
x=np.random.randint(5)
while(True):
  a=int(input("Enter a random number : if it match then you win :: ") )
  if a==x:
    print("You win")
    break;40
  elif(a>x):
    print("large number")
  else:
    print("small number")
    guess=guess+1
print(f"\033[34mYou took no of guess ={guess}")

